@startuml
'https://plantuml.com/state-diagram
hide empty description

state covered
state flagged
state revealed

[*] -> covered

covered ---> flagged : switch flag
flagged ---> covered : switch flag

covered ---> revealed : reveal
revealed ---> covered : put on cover

revealed -> [*] : level ends

@enduml