<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\SnekSweeperCore\SnekSweeperCore.csproj" />
      <ProjectReference Include="..\..\src\SnekGameDevKit\SnekGameDevKit.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="SaveLoad\Fixtures\**\*.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AwesomeAssertions" Version="9.5.0" />
      <PackageReference Include="Dumpify" Version="0.6.6" />
      <PackageReference Include="TUnit" Version="1.63.25" />
    </ItemGroup>

</Project>
