// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace SnekSweeper.NativeTools
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "ms_toollib_cs";





        [DllImport(__DllName, EntryPoint = "free_i32_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_i32_buffer(SnekSweeper.NativeTools.ByteBuffer* buffer);

        [DllImport(__DllName, EntryPoint = "lay_mine_solvable_cs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SnekSweeper.NativeTools.ByteBuffer* lay_mine_solvable_cs(nuint rows, nuint columns, nuint mine_num, nuint x0, nuint y0, nuint max_times);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }



}
