@startuml
'https://plantuml.com/state-diagram

hide empty description

state "regular instantiated" as regularInstantiated
state "fixed instantiated" as fixedInstantiated
state "game start" as gameStart
state win
state lose

[*] --> regularInstantiated : enter level from main menu
[*] --> fixedInstantiated : enter level from history record

regularInstantiated --> gameStart : first click
fixedInstantiated --> gameStart : first click

gameStart --> win : judged by referee
gameStart --> lose : judged by referee

win --> [*]
lose --> [*]

@enduml